import { safeImageSrc } from "@/lib/assessments/safe-image-src";
import type { ReportEmailChrome } from "@/lib/assessments/wave-228-flags";
import { escapeHtml } from "@/lib/templates/interpolate-content-html";

export const REPORT_EMAIL_LOGO_CID = "su-report-logo-v1";
export const REPORT_EMAIL_LOGO_SRC = `cid:${REPORT_EMAIL_LOGO_CID}`;

export type CoachBylineState = "none" | "name-only" | "image-and-name";

export interface ReportEmailChromeResult {
  coverBrandHtml: string;
  footerCellHtml: string;
  bylineState: CoachBylineState;
}

export function buildReportEmailChrome(input: {
  chrome: ReportEmailChrome;
  coachName?: string | null;
  coachLogoUrl?: string | null;
  escapedDate: string;
}): ReportEmailChromeResult {
  if (input.chrome === "legacy") {
    return {
      coverBrandHtml:
        '<div style="font-weight:800;letter-spacing:0.04em;font-size:14px;color:#ffffff;margin-bottom:14px;">SCALING UP</div>',
      footerCellHtml:
        `<td align="center" style="padding:18px 32px 26px;font-size:11px;color:#6b6480;">${input.escapedDate} &middot; Generated by Scaling Up Platform</td>`,
      bylineState: "none",
    };
  }

  const displayName = (input.coachName ?? "").trim();
  const imageSrc = displayName ? safeImageSrc(input.coachLogoUrl) : null;
  const escapedName = escapeHtml(displayName);
  const escapedImageSrc = imageSrc ? escapeHtml(imageSrc) : null;
  const bylineState: CoachBylineState =
    displayName === ""
      ? "none"
      : escapedImageSrc
        ? "image-and-name"
        : "name-only";
  const coverImage = escapedImageSrc
    ? `<td style="vertical-align:middle;padding-right:10px;"><img src="${escapedImageSrc}" alt="" width="44" style="display:block;border:0;outline:none;max-height:44px;max-width:200px;height:auto;width:auto;" /></td>`
    : "";
  const footerImage = escapedImageSrc
    ? `<td style="vertical-align:middle;padding-right:8px;"><img src="${escapedImageSrc}" alt="" width="28" style="display:block;border:0;outline:none;max-height:28px;max-width:120px;height:auto;width:auto;" /></td>`
    : "";
  const coverByline =
    bylineState === "none"
      ? ""
      : `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:12px;"><tr>${coverImage}<td style="vertical-align:middle;color:#ffffff;font-size:13px;">Coached by ${escapedName}</td></tr></table>`;
  const footerByline =
    bylineState === "none"
      ? ""
      : `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:10px;"><tr>${footerImage}<td style="vertical-align:middle;color:#ffffff;font-size:12px;">Coached by ${escapedName}</td></tr></table>`;
  const coverBrandHtml =
    `<img src="${REPORT_EMAIL_LOGO_SRC}" alt="Scaling Up" width="180" style="display:block;border:0;outline:none;max-width:180px;height:auto;" />${coverByline}`;
  const footerCellHtml =
    `<td style="background:#522583;padding:18px 32px 20px;color:#ffffff;">` +
    `<img src="${REPORT_EMAIL_LOGO_SRC}" alt="Scaling Up" width="120" style="display:block;border:0;outline:none;max-width:120px;height:auto;" />` +
    `${footerByline}<div style="margin-top:10px;font-size:11px;color:#ffffff;opacity:0.82;">${input.escapedDate} &middot; Generated by Scaling Up Platform</div>` +
    `</td>`;

  return { coverBrandHtml, footerCellHtml, bylineState };
}
