import {
  REPORT_EMAIL_LOGO_CID,
  REPORT_EMAIL_LOGO_SRC,
  buildReportEmailChrome,
} from "@/lib/assessments/report-email-chrome";

describe("buildReportEmailChrome", () => {
  it("keeps the exact legacy fragments", () => {
    expect(
      buildReportEmailChrome({
        chrome: "legacy",
        coachName: "Alex Coach",
        coachLogoUrl: "https://images.example/coach.png",
        escapedDate: "August 3, 2026",
      }),
    ).toEqual({
      coverBrandHtml:
        '<div style="font-weight:800;letter-spacing:0.04em;font-size:14px;color:#ffffff;margin-bottom:14px;">SCALING UP</div>',
      footerCellHtml:
        '<td align="center" style="padding:18px 32px 26px;font-size:11px;color:#6b6480;">August 3, 2026 &middot; Generated by Scaling Up Platform</td>',
      bylineState: "none",
    });
  });

  it("renders Scaling Up before an escaped image-and-name byline", () => {
    const result = buildReportEmailChrome({
      chrome: "gh228",
      coachName: "Alex <Coach>",
      coachLogoUrl: 'https://images.example/a"b.png',
      escapedDate: "August 3, 2026",
    });

    expect(result.coverBrandHtml.indexOf(REPORT_EMAIL_LOGO_SRC)).toBeLessThan(
      result.coverBrandHtml.indexOf("Coached by"),
    );
    expect(result.coverBrandHtml).toContain("Alex &lt;Coach&gt;");
    expect(result.coverBrandHtml).toContain('alt=""');
    expect(result.footerCellHtml).toContain(`cid:${REPORT_EMAIL_LOGO_CID}`);
    expect(result.footerCellHtml).toContain(
      "https://images.example/a&quot;b.png",
    );
    expect(result.footerCellHtml).toContain(
      "Coached by Alex &lt;Coach&gt;",
    );
    expect(result.bylineState).toBe("image-and-name");
  });

  it.each([
    ["http://images.example/coach.png", "name-only"],
    ["javascript:alert(1)", "name-only"],
    [null, "name-only"],
  ] as const)("degrades rejected image %p to %s", (coachLogoUrl, state) => {
    const result = buildReportEmailChrome({
      chrome: "gh228",
      coachName: "Alex Coach",
      coachLogoUrl,
      escapedDate: "August 3, 2026",
    });

    expect(result.bylineState).toBe(state);
    expect(result.coverBrandHtml).toContain("Coached by Alex Coach");
    expect(result.coverBrandHtml).not.toContain(String(coachLogoUrl));
  });

  it("never renders an image without a usable coach name", () => {
    const result = buildReportEmailChrome({
      chrome: "gh228",
      coachName: "   ",
      coachLogoUrl: "https://images.example/coach.png",
      escapedDate: "August 3, 2026",
    });

    expect(result.bylineState).toBe("none");
    expect(result.coverBrandHtml).not.toContain("images.example");
    expect(result.coverBrandHtml).not.toContain("Coached by");
  });
});
