import type { SummaryReportDefinition } from "./types";

export const SUMMARY_REPORT_REGISTRY: readonly SummaryReportDefinition[] = [
  {
    type: "SCALING_CEO_FULL",
    templateAliases: ["scaling-up-full"],
    label: "Scaling Up · CEO Full",
    description: "Compare one CEO with an explicitly selected leadership team.",
    implemented: true,
    roles: [
      { role: "CEO", min: 1, max: 1 },
      { role: "TEAM", min: 0, max: null },
    ],
    hasRemarksStep: false,
    rendererVersion: "scaling-ceo-full-pdf-v1",
  },
  {
    type: "SCALING_CONDENSED_CEO",
    templateAliases: ["scaling-up-full"],
    label: "Scaling Up · Condensed CEO",
    description: "Create a two-page CEO score and peer appendix.",
    implemented: true,
    roles: [{ role: "CEO", min: 1, max: 1 }],
    hasRemarksStep: false,
    rendererVersion: "scaling-condensed-ceo-html-v1",
  },
  {
    type: "SCALING_SELF_COMPARISON",
    templateAliases: ["scaling-up-full"],
    label: "Scaling Up · Self Comparison",
    description: "Compare one current report with one earlier report for the same person.",
    implemented: true,
    roles: [
      { role: "FOCUS", min: 1, max: 1 },
      { role: "EARLIER", min: 1, max: 1 },
    ],
    hasRemarksStep: false,
    rendererVersion: "scaling-self-comparison-html-v1",
  },
  {
    type: "LVA_CEO_FULL",
    templateAliases: ["leadership-vision-alignment"],
    label: "Leadership Vision Alignment · CEO Full",
    description: "Combine one CEO and selected team responses into the full alignment report.",
    implemented: false,
    roles: [
      { role: "CEO", min: 1, max: 1 },
      { role: "TEAM", min: 0, max: null },
    ],
    hasRemarksStep: false,
    rendererVersion: "lva-ceo-full-pdf-v1",
  },
  {
    type: "QSP_V1_CEO_FULL",
    templateAliases: ["qsp-v1"],
    label: "Quarterly Session Preparation v1 · CEO Full",
    description: "Combine one CEO and selected team responses into the v1 quarterly summary.",
    implemented: false,
    roles: [
      { role: "CEO", min: 1, max: 1 },
      { role: "TEAM", min: 0, max: null },
    ],
    hasRemarksStep: true,
    rendererVersion: "qsp-v1-ceo-full-pdf-v1",
  },
  {
    type: "QSP_V2_CEO_FULL",
    templateAliases: ["qsp-v2"],
    label: "Quarterly Session Preparation v2 · CEO Full",
    description: "Combine one CEO and selected team responses into the v2 quarterly summary.",
    implemented: false,
    roles: [
      { role: "CEO", min: 1, max: 1 },
      { role: "TEAM", min: 0, max: null },
    ],
    hasRemarksStep: true,
    rendererVersion: "qsp-v2-ceo-full-pdf-v1",
  },
  {
    type: "ROCKEFELLER_FULL",
    templateAliases: ["RockHabits"],
    label: "Rockefeller Habits · Full Report",
    description: "Combine one or more team reports into the five-page Rockefeller Habits summary.",
    implemented: false,
    roles: [{ role: "TEAM", min: 1, max: null }],
    hasRemarksStep: false,
    rendererVersion: "rockefeller-full-pdf-v1",
  },
];
