/**
 * Wave E — BrandedReport footer cleanup (#25) + report-config score-table
 * gating (#24), on-screen render path.
 *
 * #25: the footer must be EXACTLY submission date · SU logo · "Generated by
 *      Scaling Up Platform" — no submission id / version / content hash /
 *      "Confidential" provenance line, and the date is the report's
 *      submittedAt (NOT a fresh `new Date()`).
 * #24: the "All sections" score table is shown only when
 *      reportConfigFor(report.templateAlias).showScoreTable is true — hidden
 *      for the Rockefeller alias ("RockHabits"), shown for the default /
 *      scored aliases.
 */

import { render, screen } from "@testing-library/react";
import { BrandedReport } from "@/components/assessments/BrandedReport";
import type { RespondentReport } from "@/lib/assessments/respondent-report";
import type { ScoreResult } from "@/lib/assessments/scoring";

// ── Fixture (mirrors branded-report.test.tsx baseReport shape) ──────────────

function baseReport(overrides: Partial<RespondentReport> = {}): RespondentReport {
  const result: ScoreResult = {
    perQuestion: [{ stableKey: "q1", value: 3, achieved: true }],
    perSection: [
      {
        stableKey: "s1",
        name: "The executive team is healthy",
        totalPoints: 6,
        averagePoints: 2,
        achievedCount: 1,
        totalCount: 1,
      },
    ],
    overallTotal: 6,
    overallAverage: 2,
    countAchieved: 1,
    tier: { label: "Strong", message: "Aligned." },
    tierMetricValue: 2,
    unansweredKeys: [],
  };
  return {
    respondentName: "Sarah Chen",
    jobTitle: "Chief Executive Officer",
    companyName: "Northwind Logistics",
    assessmentName: "Rockefeller Habits Checklist",
    campaignLabel: null,
    submittedAt: new Date("2026-05-01T12:00:00Z"),
    result,
    sections: [
      { stableKey: "s1", name: "The executive team is healthy", questions: [{ stableKey: "q1" }] },
    ],
    questionByKey: { q1: "Members understand each other's styles" },
    questionsByKey: {
      q1: { type: "SLIDER_LIKERT", label: "Members understand each other's styles", sectionStableKey: "s1", min: 0, max: 3 },
    },
    rawAnswers: [{ stableKey: "q1", value: 3 }],
    scoringConfig: {
      tierMetric: "countAchieved",
      passThreshold: 1,
      tiers: [{ minMetric: 0, label: "Strong", message: "Aligned." }],
    },
    provenance: {
      submissionId: "sub-123",
      versionId: "ver-456",
      contentHash: "abcdef0123456789",
      templateName: "Rockefeller Habits Checklist",
    },
    degraded: false,
    ...overrides,
  };
}

// ════════════════════════════════════════════════════════════════════════════
// #25 — footer cleanup
// ════════════════════════════════════════════════════════════════════════════

describe("BrandedReport — footer (#25)", () => {
  it("credit line reads exactly 'Generated by Scaling Up Platform'", () => {
    render(<BrandedReport report={baseReport()} />);
    const footer = screen.getByTestId("report-footer");
    expect(footer.textContent).toMatch(/Generated by Scaling Up Platform/);
  });

  it("shows the submission date (report.submittedAt, not new Date())", () => {
    render(<BrandedReport report={baseReport({ submittedAt: new Date("2026-05-01T12:00:00Z") })} />);
    const footer = screen.getByTestId("report-footer");
    expect(footer.textContent).toMatch(/2026/);
    // The fixed submitted month, formatted via Intl en-US, must appear.
    expect(footer.textContent).toMatch(/May/);
  });

  it("drops the provenance span (no submission id / version / hash / Confidential)", () => {
    render(<BrandedReport report={baseReport()} />);
    const footer = screen.getByTestId("report-footer");
    expect(footer.textContent).not.toMatch(/Submission /);
    expect(footer.textContent).not.toMatch(/sub-123/);
    expect(footer.textContent).not.toMatch(/ver-456/);
    expect(footer.textContent).not.toMatch(/abcdef0/);
    expect(footer.textContent).not.toMatch(/Confidential/i);
    expect(footer.textContent).not.toMatch(/· v\d/);
  });

  it("keeps the Scaling Up logo image", () => {
    const { container } = render(<BrandedReport report={baseReport()} />);
    const footer = screen.getByTestId("report-footer");
    expect(footer.querySelector("img.su-logo")).not.toBeNull();
    expect(container).toBeTruthy();
  });
});

// ════════════════════════════════════════════════════════════════════════════
// #24 — score table gated by report-config
// ════════════════════════════════════════════════════════════════════════════

describe("BrandedReport — score table gating (#24)", () => {
  it("hides the All-sections score table for the Rockefeller alias", () => {
    render(<BrandedReport report={baseReport({ templateAlias: "RockHabits" })} />);
    expect(screen.queryByTestId("report-scores-table")).toBeNull();
  });

  it("shows the score table for a default/scored alias (no alias)", () => {
    render(<BrandedReport report={baseReport({ templateAlias: undefined })} />);
    expect(screen.getByTestId("report-scores-table")).not.toBeNull();
  });

  it("shows the score table for the scaling-up-full alias", () => {
    render(<BrandedReport report={baseReport({ templateAlias: "scaling-up-full" })} />);
    expect(screen.getByTestId("report-scores-table")).not.toBeNull();
  });
});
