/**
 * Assessment v7.6 — ReportFooter (Jeff July-10 #63/#67/#73/#78/#81).
 *
 * The single footer for all three report renderers (BrandedReport,
 * QualitativeReport, GroupReport). Extracted because the three emitted
 * byte-identical footer markup — the same duplication that justified pulling
 * `CoachLogo` out in PR #203 — and this change had to touch all three.
 *
 * ORDER IS LOAD-BEARING, do not reorder these children:
 *   Scaling Up mark → coach byline → date → credit line.
 *
 * The coach block is a SUBORDINATE PROVENANCE BYLINE, not a co-brand peer (see
 * the superseded-G7 note in docs/specs/v7.6/13-assessment-brand-and-results-report.md).
 * The footer expresses that in the DOM rather than in CSS because its layout is
 * order-sensitive in BOTH directions:
 *
 *   - desktop (>720px): `justify-content: space-between` — first child sits far LEFT
 *   - narrow  (<=720px): `flex-direction: column`        — first child sits ON TOP
 *
 * The narrow path is not only a phone concern: A4 print at 14mm margins is
 * ~688 CSS px, below the 720px breakpoint, so printed/saved PDFs take it too.
 * A CSS `order` would fix both widths visually while leaving the DOM (and
 * therefore screen-reader and tab order) wrong, and would make the ordering
 * untestable at the jsdom layer — `next/jest` stubs CSS, so DOM order is the
 * only thing a unit test can see. Guarded by
 * __tests__/components/assessments/report-footer-order.test.tsx.
 *
 * `dateLabel` is passed pre-formatted: each renderer already owns its own
 * formatter (they happen to agree on en-US long dates today, but the footer is
 * not the right place to centralise that decision).
 */

import { CoachLogo } from "@/components/assessments/CoachLogo";

const LOGO_SRC = "/brand/su-logo-white.svg";

export function ReportFooter({
  dateLabel,
  coachLogoUrl,
  coachName,
  testId,
}: {
  /** Already-formatted date string (each renderer owns its own formatter). */
  dateLabel: string;
  coachLogoUrl?: string | null;
  coachName?: string | null;
  /** "report-footer" (per-respondent) or "group-report-footer" (cohort). */
  testId: string;
}) {
  return (
    <footer className="su-report-footer" data-testid={testId}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        className="su-logo"
        src={LOGO_SRC}
        alt="Scaling Up"
        width={120}
        height={22}
      />
      {/* Coach byline — subordinate to the SU mark; renders nothing when absent. */}
      <CoachLogo url={coachLogoUrl} name={coachName} variant="footer" />
      <span className="su-report-submitted-date">{dateLabel}</span>
      <span className="su-report-confidential">
        Generated by Scaling Up Platform
      </span>
    </footer>
  );
}

export default ReportFooter;
